### ISSUE TITLE
4K触屏问题

### ISSUE THREAD

**Issue by ygjsz** [flyingchase/Hackinosh-XPS7590#1]
如题，触屏不能驱动，有啥好的解决方案吗

**Comment by flyingchase** [comment]
我的 EFI也是参考各位大佬汇总的修改的， 触控屏貌似是由于耗电和睡眠后黑屏从而关闭了， 你可以参考一下这位老哥的 EFI，https://github.com/Liyunlock/DELL-XPS-15-7590-4K-Touchscreen_OpenCore_Hackintosh 这个在 bios开启 touchScreen 后可以正常使用，我之前就是用他的，后来更新系统后需求雷电三就换了别人的。
