### ISSUE TITLE
大佬好，我也是XPS7590，I5-9300H核显版本，有问题想要咨询

### ISSUE THREAD

**Issue by zhsida** [flyingchase/Hackinosh-XPS7590#4]
如果你方便的话能加我下QQ1796798404吗，万分感谢，如果不想加的话能给个7590的组织群吗。有一些小问题想要学一下

**Comment by flyingchase** [comment]
去群里问吧 大佬比较多 我也是汇总各种解决方案来完善的  群号：929644389
